### ISSUE TITLE
Support preload for resource

### ISSUE THREAD

**Issue by yesvods** [KidkArolis/jetpack#42]
It's important to support resource preload when page is served by SSR, which makes meaningful performance for UX.

**Comment by yesvods** [comment]
Closed due to no more feedback.

**Comment by KidkArolis** [comment]
Generally, jetpack is a little more aimed at SPA and a little lower level. For SSR you might find some existing solutions like Next.js to be a better fit. Where you considering using jetpack for SSR? How do you achieve resource preloading with webpack? Since jetpack makes no assumptions about how you do routing, I'm not sure it would know when to preload what.
